[tools]
pipx = "latest"
pnpm = "latest"
rust = "latest"
rust-analyzer = "latest"
uv = "latest"
yarn = "latest"
node = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
